rust-osdev/xhci

CHANGELOG.md
src/registers/runtime.rs

- chore: rename to `set_event_ring_dequeue_pointer`
- fix: typo
bors r+

chore: rename `set` method

---

release.toml

The master branch is protected.
bors r+

chore: disable to push from `cargo release`

---

rustfmt.toml

chore: add `rustfmt.toml`

---

rustfmt.toml

- chore: add `rustfmt.toml`
- chore: format doc comments
- fix: forgot to remove the license notation

chore: edit `rustfmt.toml`

---

CHANGELOG.md
src/lib.rs

- chore: reexport `Error`
bors r+

chore: reexport `error::Error` as `Error`.

---

rustfmt.toml

chore: use `imports_granularity`

---

CHANGELOG.md
Cargo.toml
src/extended_capabilities/mod.rs
src/registers/capability.rs
src/registers/doorbell.rs
src/registers/mod.rs
src/registers/operational.rs
src/registers/runtime.rs

- chore: update the version of the `accessor` crate
- chore: panic immediately

chore: panics if it fails to create an accessor

---

.github/workflows/rust.yml

chore: deny the missing `Copy` implementations

---

.github/workflows/rust.yml
CHANGELOG.md
src/extended_capabilities/mod.rs
src/registers/capability.rs
src/registers/mod.rs
src/registers/operational.rs

chore: deny missing `Debug` implementations

---

.github/workflows/rust.yml
src/lib.rs

rustdoc does not use `RUSTFLAGS` variable. It only accepts the attribute
style.
bors r+

chore: write the list of lints in `lib.rs`

---

CHANGELOG.md
Cargo.toml
README.md

- chore: bump the version to 0.4.1
- fix: forgot to update the `README.md`
bors r+

chore: release the version 0.4.1

---

src/lib.rs

chore: deny non-ascii idents

---

src/lib.rs

chore: deny the pointer structural match

---

src/lib.rs

chore: deny the unaligned references

---

src/lib.rs

chore: deny the unused crate dependencies

---

src/lib.rs

chore: deny the unused extern crates

---

src/lib.rs

chore: deny the unused import braces

---

src/lib.rs

chore: deny the unused lifetimes

---

CHANGELOG.md
src/ring/trb/command.rs

- fix: the parameter was a mutable reference
- fix: the parameter was a mutable reference
bors r+

fix: getters take immutable references

---

CHANGELOG.md
Cargo.toml

chore: bump the version to 0.5.2

---

src/registers/operational.rs

chore: split method definitions of Port PM Status and Control

---

CHANGELOG.md
src/registers/capability.rs

While [documentation](https://edc.intel.com/content/www/ru/ru/design/products-and-solutions/processors-and-chipsets/comet-lake-u/intel-400-series-chipset-on-package-platform-controller-hub-register-database/structural-parameters-2-hcsparams2-offset-8/) says max-scratchpad-buffers-hi is range `25:21`(`21..=25` in Rust), `25:20` was specified (and fixed).

fix(StructuralParameters2): Bit range in max_scratchpad_buffers_hi

---

.clippy.toml

Functions should be small, but sometimes we cannot follow the rule,
especially for enums.

Remove the line number limitation

---

CHANGELOG.md
src/ring/trb/command.rs
src/ring/trb/event.rs
src/ring/trb/mod.rs
src/ring/trb/transfer.rs

Added `TryFrom<[u32; 4]>` to Command/Transfer TRB structs with Rsvdz checks.

feat: added TryFrom<[u32; 4]> to Command/Transfer TRB structs

---

CHANGELOG.md
src/registers/doorbell.rs
src/registers/operational.rs
src/registers/runtime.rs

For these registers it is fine (and even correct[1]) to perform a write
without a read. This allows code to be a bit more efficient.
[1] RsvdZ bits are reserved for future RW1C bits. Software should write
0 to them by default.

Implement Default for registers without RsvdP bits

---

CHANGELOG.md
src/macros.rs

This is necessary to avoid clearing certains bits, such as Port
Enable/Disable.
Supersedes #146

Add set_0_* to rw1c! macro

---

CHANGELOG.md
src/ring/trb/transfer.rs

As defined in xHCI Specification [6.4.1.1 Normal TRB](https://www.intel.com/content/dam/www/public/us/en/documents/technical-specifications/extensible-host-controler-interface-usb-xhci.pdf#page=465) , `Normal TRB`'s first 32bit is `Data Buffer Pointer Lo`, and next 32bit is `Data Buffer Pointer Hi`.
Before this patch, the calculation of `Data Buffer Pointer` in Normal TRB is wrong. So I fixed it.
Thank you.

Fix wrong calculation of data_buffer_pointer of transfer::Normal

---

src/macros.rs
src/registers/capability.rs
src/registers/doorbell.rs
src/registers/mod.rs

This is a resolution of https://github.com/rust-osdev/xhci/issues/164.
I couldn't implement method chaining for context handlers, due to their `dyn` nature.

PR for Misc Issue #164

---

CHANGELOG.md

Changelog for #170
