- .clippy.toml
- .github/workflows/rust.yml
- build: run CI on every push and pull request
- build: deny all rustc warnings
- build: rewrite CI script
bors r+
> build: rewrite CI script

- CHANGELOG.md
- Cargo.toml
- README.md
- release.toml
- chore: fill `Cargo.toml`
- fix: typo
- chore: add `README.md`
- chore: add CHANGELOG.md
- chore: add `release.toml`
- chore: add markers to `CHANGELOG.md`
bors r+
> chore: prepare for publishing

- release.toml
> chore: dev version is not necessary

- release.toml
> Revert "chore: dev version is not necessary"

- CHANGELOG.md
> chore: add a change log

- README.md
- chore: add badges
- chore: add a badge to docs.rs
- fix: wrong URL
- fix: wrong url
bors r+
> chore: add badges to `README.md`

- CHANGELOG.md
- Cargo.toml
> chore: release 0.2.0

- Cargo.toml
> fix: wrong categories

- src/error.rs
> fix: forgot to implement `Debug` for `Error`

- CHANGELOG.md
- Cargo.toml
> chore: bump the version to 0.2.2

- CHANGELOG.md
- src/registers/operational.rs
- fix: wrong bit index was specified
bors r+
> fix: wrong bit was updated

- CHANGELOG.md
- Cargo.toml
> chore: update the version to 0.2.3

- CHANGELOG.md
- src/extended_capabilities/mod.rs
- src/extended_capabilities/usb_legacy_support_capability.rs
- src/lib.rs
- feat: implement the USB Legacy Support Capability
bors r+
> feat: add the USB Legacy Support Capability

- CHANGELOG.md
- Cargo.toml
> chore: bump the version to 0.2.4

- CHANGELOG.md
- src/error.rs
- src/extended_capabilities/usb_legacy_support_capability.rs
- src/registers/capability.rs
- src/registers/doorbell.rs
- src/registers/operational.rs
- src/registers/runtime.rs
> chore: implement `Copy` and `Clone` for register types

- CHANGELOG.md
- Cargo.toml
> chore: release 0.2.5

- CHANGELOG.md
- Cargo.toml
- chore: bump the version to 0.2.6
bors r+
> chore: release 0.2.6

- .github/workflows/rust.yml
- CHANGELOG.md
- src/registers/operational.rs
> ci: disallow document defects

- CHANGELOG.md
- Cargo.toml
> chore: bump the version to 0.3.0

- CHANGELOG.md
- Cargo.toml
- chore: bump the version to 0.4.0
bors r+
> chore: bump the version to 0.4.0

- CHANGELOG.md
- src/extended_capabilities/mod.rs
- src/registers/mod.rs
> fix: wrong documentations

- .gitignore
> chore: ignore backup files from tracking with git

- .github/workflows/rust.yml
> chore: deny the explicit outlives requirements

- .github/workflows/rust.yml
> chore: deny macro use extern crate

- .github/workflows/rust.yml
> style: deny the misuse of meta variables

- .github/workflows/rust.yml
- src/lib.rs
- style: deny the missing doc code examples
- Revert "style: deny the missing doc code examples"
- style: deny the missing documentation code examples
bors r+
> style: deny the missing documentation code examples

- .github/workflows/rust.yml
- CHANGELOG.md
- src/context.rs
- src/extended_capabilities/mod.rs
- src/lib.rs
To use lints related to the rustdoc.
bors r+
> docs: add examples

- src/lib.rs
> chore: deny the private doc tests

- src/extended_capabilities/mod.rs
- src/lib.rs
> chore: deny the single use lifetimes

- src/lib.rs
> chore: deny the trivial casts

- src/lib.rs
> chore: deny the unreachable publics

- src/lib.rs
- src/ring/trb/mod.rs
> chore: deny the unused qualifications

- src/ring/trb/transfer.rs
> refactor: define `transfer_trb` and `transfer_trb_with_default` macros

- CHANGELOG.md
- src/ring/trb/transfer.rs
- fix: add the missing getters
bors r+
> fix: implement the missing getters of the Transfer TRBs

- CHANGELOG.md
- Cargo.toml
- chore: bump the version to 0.5.0
bors r+
> chore: bump the version to 0.5.0

- CHANGELOG.md
- Cargo.toml
- chore: bump the version to 0.5.1
bors r+
> chore: bump the version to 0.5.1

- CHANGELOG.md
- src/ring/trb/mod.rs
- chore: implement `From` for the `Allowed` enum
bors r+
> feat: implement `From` for `Allowed`

- CHANGELOG.md
- src/extended_capabilities/hci_extended_power_management.rs
> chore: rewrite `HciExtendedPowerManagement`

- CHANGELOG.md
- Cargo.toml
- Add a changelog
- Release 0.8.5
> Release 0.8.5

- CHANGELOG.md
- Cargo.toml
- Add a changelog
- Release 0.8.6
> Release 0.8.6

- CHANGELOG.md
- Cargo.toml
- Add a changelog
- Release 0.8.7
> Release 0.8.7

- .github/workflows/rust.yml
- CHANGELOG.md
- src/lib.rs
See https://github.com/actions-rs/clippy-check/issues/2#issuecomment-1625984127.
Closes #155.
> Switch Clippy runner on CI

- src/lib.rs
- src/registers/mod.rs
- removed deprecated clippy check option
> removed deprecated clippy check option
